### ISSUE TITLE
Adjust readme order + issue with contract deploy cmd

### ISSUE THREAD

**Issue by jmahhh** [ethereum-optimism/superchainerc20-starter#57]
1) It is not clear from the readme that you're supposed to run `pnpm contracts:update:rpcs` and especially `pnpm contracts:deploy:token` before `pnpm dev` as the latter requires `deployment.json` to exist. 
2) Running `pnpm contracts:deploy:token` in the root folder gave me `sh: 1: source: not found`. I resorted to running `forge script scripts/SuperchainERC20Deployer.s.sol --broadcast --private-key $DEPLOYER_PRIVATE_KEY` in the `contracts` folder and manually replaced `$DEPLOYER_PRIVATE_KEY` as it doesn't seem to work properly with the `.env` file. 

On WSL if it matters.

**Comment by tremarkley** [comment]
The root cause of both 1 and 2 are because `source` command is not available in your environment. I just merged: https://github.com/ethereum-optimism/superchainerc20-starter/pull/58 which should resolve this for you and the readme instructions should work as expected now. Let me know how it goes!
