### ISSUE TITLE
bash script for generating superchain registry rpc urls

### ISSUE THREAD

**Issue by tremarkley** [ethereum-optimism/superchainerc20-starter#6]

**Comment by nitaliano** [comment]
sorry if this is painfully obvious already or if you were already planning on using this file https://github.com/ethereum-optimism/superchain-registry/blob/main/chainList.json i just didn't realize it existed until last week. The rpc urls also exist in it.

**Comment by tremarkley** [comment]
@nitaliano I am pulling in this file https://raw.githubusercontent.com/ethereum-optimism/superchain-registry/main/superchain/configs/configs.json in the bash script: https://github.com/ethereum-optimism/superchainerc20-starter/pull/20/files#diff-ce84f7888b2fcc13c9cdee2fcfafafff0f035ce63445ddb3bfab320af0ba5a20R10

**Comment by nitaliano** [comment]
sounds good! i think we should expect the `config.json` to have breaking changes to it overtime nothing we can really do to avoid it from the README https://github.com/ethereum-optimism/superchain-registry/tree/main?tab=readme-ov-file#more-about-the-superchain-registry it sounds like the top level toml and json file should be safe
